export const pcRouteTitles = {
  '/': '首页看板',
  '/demo': 'Demo 控制台',
  '/master/materials': '基础资料-物料列表',
  '/master/colors': '基础资料-色级列表',
  '/master/customers': '基础资料-客户列表',
  '/master/units': '基础资料-单位列表',
  '/master/dict': '基础资料-数据字典',
  '/master/config/workshops': '生产资料-车间',
  '/master/config/lines': '生产资料-产线',
  '/master/config/calendar': '生产资料-生产日历表',
  '/master/config/line-product-relations': '生产资料-产线与产品关系表',
  '/master/config/product-group-relations': '生产资料-产品组关系表',
  '/master/config/forms': '生产资料-生产表单',
  '/master/config/processes': '生产资料-生产工序',
  '/master/config/crafts': '生产资料-生产工艺',
  '/master/config/bom': '生产资料-物料清单',
  '/sales-orders': '销售订单',
  '/production-orders': '生产订单',
  '/schedule': '计划排程',
  '/work-orders': '批次工单',
  '/formulas': '配方单',
  '/records': '生产记录',
  '/inventory': '库存管理-即时库存',
  '/inventory/reservations': '库存管理-MRP库存占用单',
  '/inventory/inbound': '库存管理-预计入库登记',
  '/inventory/outbound': '库存管理-预计出库登记',
  '/barcodes': '条码档案',
  '/tanks': '储罐档案',
};
